### ISSUE TITLE
Cover all the mechanisms on BGG.

### ISSUE THREAD

**Issue by blinks** [blinks/pattern#1]
See https://boardgamegeek.com/browse/boardgamemechanic

- [ ] Acting
- [x] Action / Movement Programming
- [x] Action Point Allowance System
- [ ] Area Control / Area Influence
- [ ] Area Enclosure
- [x] Area Movement
- [ ] Area-Impulse
- [x] Auction/Bidding
- [ ] Betting/Wagering
- [ ] Campaign / Battle Card Driven
- [ ] Card Drafting
- [ ] Chit-Pull System
- [x] Co-operative Play
- [x] Commodity Speculation
- [ ] Crayon Rail System
- [x] Deck / Pool Building
- [x] Dice Rolling
- [ ] Grid Movement
- [ ] Hand Management
- [ ] Hex-and-Counter
- [ ] Line Drawing
- [ ] Memory
- [ ] Modular Board
- [ ] Paper-and-Pencil
- [ ] Partnerships
- [ ] Pattern Building
- [ ] Pattern Recognition
- [ ] Pick-up and Deliver
- [x] Player Elimination
- [x] Point to Point Movement
- [ ] Press Your Luck
- [x] Rock-Paper-Scissors
- [ ] Role Playing
- [ ] Roll / Spin and Move
- [ ] Route/Network Building
- [ ] Secret Unit Deployment
- [x] Set Collection
- [ ] Simulation
- [ ] Simultaneous Action Selection
- [ ] Singing
- [x] Stock Holding
- [ ] Storytelling
- [ ] Take That
- [ ] Tile Placement
- [x] Time Track
- [ ] Trading
- [ ] Trick-taking
- [ ] Variable Phase Order
- [ ] Variable Player Powers
- [ ] Voting
- [x] Worker Placement

**Comment by garykac** [comment]
Dice pull as a variant of chit pull
