### ISSUE TITLE
[Pattern] Blind Test

### ISSUE THREAD

**Issue by garykac** [blinks/pattern#30]
- [ ] Confidence, from 1 to 3 stars.
- [ ] Context (followed by `* * *`)
- [ ] Problem (in bold)
- [ ] Forces
- [ ] Solution (in bold, followed by `* * *`)
- [ ] "How and why" explanatory text.

There are a surprisingly large number of designers who finish the rules and then start looking for blind playtests.

This may be due to the lack of proper playtester nearby, but it's still a bad thing and it means those people can't be used for proper blind playtests later.

Related to #28

**Comment by blinks** [comment]
This is an excellent one. I feel like the ordering in the book will likely end up revolving around when to apply the various patterns, more than sorting by category.

**Comment by blinks** [comment]
Problem: You're unsure of the quality of your rules explanation. You're unsure of how much your presence changes the experience.

Solution: Don't be there.

**Comment by garykac** [comment]
Alternately, Matt Leacock has people video record themselves playing the game and sending him a video (with an agreement that it will never be shown to anyone else, etc).

Advantage. Lots of feedback that is hard to get. You can see the player's body language and facial expressions.

He started doing this because whenever he was in the same room as the testers, either (a) he would be tempted to "help", or (b) they would look to him, silently asking "are we doing this right?"

But being quiet and watching (if you can manage it) is a good intermediate step.

**Comment by garykac** [comment]
At GenCon, I ran "semi blind" sessions, where I explained the game at the start, but asked players to refer to the rulebook if they had questions during the game. If it took a while (or if I knew the answer wasn't in there), then I would step in.

This worked well for a few of the tests, but didn't come into play for others. I probably jumped in too often in those cases.

**Comment by blinks** [comment]
Yeah, I'm looking for an intermediate pattern between this and the high-touch early tests, where you're playing. There should be one where you're taking an active discussion role, but not actually playing -- I've found my notes in those games to be excellent, but they can't make up for playing the game myself (high-touch) or forcing others to learn it themselves (blind).

**Comment by blinks** [comment]
Those playtests sound like test-with-fallback, which might be a fourth testing pattern.
