### ISSUE TITLE
[Pattern] Create a Quickstart Guide

### ISSUE THREAD

**Issue by garykac** [blinks/pattern#39]
- [ ] Confidence, from 1 to 3 stars.
- [ ] Context (followed by `* * *`)
- [ ] Problem (in bold)
- [ ] Forces
- [ ] Solution (in bold, followed by `* * *`)
- [ ] "How and why" explanatory text.

Similar to a rulebook, a quickstart guide removes a lot of details and allowed new players to start playing the game more quickly.

If you are planning on sending your game out to anyone for blindplaytesting or review or consideration for publication, they will all appreciate this.

Ordering: after you write the rule book, but before blind playtesting.

**Comment by blinks** [comment]
Related to Rules Outline, too. I wonder about the overlap there, and whether it's useful to consider them in the same place.

**Comment by garykac** [comment]
They serve different purposes but there is a lot of overlap.

Target audience for outline is the designer.
Target audience for the quick start is a new player.
