### ISSUE TITLE
[Pattern] Solo test

### ISSUE THREAD

**Issue by garykac** [blinks/pattern#40]
- [ ] Confidence, from 1 to 3 stars.
- [ ] Context (followed by `* * *`)
- [ ] Problem (in bold)
- [ ] Forces
- [ ] Solution (in bold, followed by `* * *`)
- [ ] "How and why" explanatory text.

Even if your game is not a solo game, it is valuable to play it solo so that you can see how all the pieces fit together.

Variant, if your game requires 4 players, but you only have 2, you can have each player take on 2 "players".

This is one of the earliest test patterns - often before you show the design to anyone else.

**Comment by garykac** [comment]
Context: "You have your initial set of rules"
Problem: "Does this work as a game?"
Solution: as above

**Comment by blinks** [comment]
Perhaps "Minimal Test" -> to encapsulate your variant of two players testing a six-player game, etc.

Should include all the caveats around things to trust less in this kind of test, how to make it easier to fill those roles, and how to also minimize components and effort for a testable Throwaway Prototype.

**Comment by blinks** [comment]
This might also be related to "Thought Test", where you just play it in your head, but I've found that it helps (somehow) to be manipulating physical components -- so perhaps that needs to be called out here.

**Comment by garykac** [comment]
"Thought Test" should be an anti-pattern. It's too easy to miss stuff that becomes obvious when you're moving physical components. But everyone thinks they're smart enough to think it out in their head.

**Comment by blinks** [comment]
Further edits in the file, or as new bugs.
