### ISSUE TITLE
[Pattern] Provide "shared" resources and goals

### ISSUE THREAD

**Issue by garykac** [blinks/pattern#42]
- [ ] Confidence, from 1 to 3 stars.
- [ ] Context (followed by `* * *`)
- [ ] Problem (in bold)
- [ ] Forces
- [ ] Solution (in bold, followed by `* * *`)
- [ ] "How and why" explanatory text.

Context: You want to make a multi-player game.
Problem: "Not a lot of player interaction. My game feels like multiplayer solitaire"
Solution: Add resources and/or goals that multiple players are competing for.

**Comment by blinks** [comment]
Yes, I like that one a lot. I also like problem statements that include sample player feedback.

**Comment by blinks** [comment]
Anti-pattern to discuss here: racing to goals when only one player can reach them [SeaFall] is not great.

**Comment by garykac** [comment]
"shared" goals isn't the right term for this. that sounds like co-op. I couldn't think of a better phrasing ATM.

**Comment by blinks** [comment]
Makes enough sense with the scare quotes to me, but yeah. Covering shared resources is a really cool angle to it, too. (I'm thinking Roads & Boats resources that anyone can pick up, or COIN resources where the US is spending the Coalition's cash.)
