### ISSUE TITLE
[Pattern] Make upkeep a reward

### ISSUE THREAD

**Issue by blinks** [blinks/pattern#48]
- [ ] Confidence, from 1 to 3 stars.
- [ ] Context (followed by `* * *`)
- [ ] Problem (in bold)
- [ ] Forces
- [ ] Solution (in bold, followed by `* * *`)
- [ ] "How and why" explanatory text.

If there's a necessary procedure in your game that's often forgotten, try to make it beneficial for the player who needs to remember it. (In Magic: The Gathering, you untap and draw at the start of your turn, which is also where all the other upkeep triggers happen -- your opponent will remind you of the harmful ones.)

**Comment by garykac** [comment]
I'm setting the stage for referencing this in the blog. "How can I fix the problem of people (sometimes) forgetting to draw customers at the start of their turn?"
